majorly improved the distribute script

diff --git a/distribute b/distribute
--- a/distribute
+++ b/distribute
@@ -1,9 +1,57 @@
 #!/bin/bash
 
-make
-cp boot.dol boot/source/hbf.dol
-make -C boot/
-cp boot/boot.dol installer/wad/00000002.app
-wine installer/WadMii.exe -input "Z:\home\chris\Projekte\homebrewfilter\installer\wad" -output "Z:\home\chris\Projekte\homebrewfilter\installer\data\install.wad"
-make -C installer
-cp installer/boot.dol HomebrewFilter/
+compile_hbf ()
+{
+	make || exit 1
+}
+
+compile_boot ()
+{
+	if [[ -e $PWD/boot.dol ]]; then
+		cp boot.dol boot/source/hbf.dol
+		make -C boot/ || exit 1
+	else	compile_hbf
+		cp boot.dol boot/source/hbf.dol
+		make -C boot/ || exit 1
+	fi
+
+}
+
+compile_installer ()
+{
+	if [[ -e boot/boot.dol ]]; then
+		cp boot/boot.dol installer/wad/00000002.app
+	else	compile_boot
+	fi
+
+	wine installer/WadMii.exe -input "Z:\home\chris\Projekte\homebrewfilter\installer\wad" -output "Z:\home\chris\Projekte\homebrewfilter\installer\data\install.wad"
+
+	sleep 5
+
+	if [[ -e installer/data/install.wad ]]; then
+		make -C installer
+	else	echo -e "--Error installer/data/install.wad not found--"
+		exit 1
+	fi
+
+}
+
+make_distribution ()
+{
+
+	if [[ -e installer/boot.dol ]]; then
+		cp installer/boot.dol HomebrewFilter/
+	else	compile_installer
+		cp installer/boot.dol HomebrewFilter/
+	fi
+
+	XREV=$(grep "define SVN_REV" svnrev/svnrev.c | gawk '{print $3}')
+
+	cp data/meta.xml.in HomebrewFilter/meta.xml
+
+	sed -e "s/@REV@/$XREV/g" -i HomebrewFilter/meta.xml
+	sed -e '/./{H;$!d;}' -e 'x;/rev37/!d;' updates >> HomebrewFilter/meta.xml
+	echo -e "\n  </long_description>\n</app>" >> HomebrewFilter/meta.xml
+}
+
+make_distribution
